In [1]:
import tensorflow as tf

In [6]:
style_layer = tf.constant([1,2,3,4,5,6,7,8], shape = (2,2,2))
style_layer

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

In [9]:
A = tf.transpose(tf.reshape(style_layer, shape = (2,4)))
A

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])>

In [10]:
AT = tf.transpose(A)
AT

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [11]:
G = tf.matmul(AT, A)
G

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 30,  70],
       [ 70, 174]])>

In [20]:
G = tf.linalg.einsum('ij, jk ->ik', AT, A)
G

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 30,  70],
       [ 70, 174]])>

In [26]:
G = tf.linalg.einsum('ij, jk ->', AT, A)
print(G)

tf.Tensor(344, shape=(), dtype=int32)
